[env]
TERM = "xterm-256color"

[shell]
args = ["--login"]
program = "/bin/zsh"

[window]
blur = true
dynamic_padding = true
opacity = 0.97
option_as_alt = "Both"

padding.x = 8
padding.y = 8

[font]
size = 14
normal.family = "SF Mono"

normal.style = "Regular"
bold.style = "Bold"
bold_italic.style = "Bold Italic"
italic.style = "Medium Italic"

